import type { Action } from './types.js';

const instanceParam = { name: 'instance', in: 'path' as const, type: 'string' as const, required: true, desc: 'Nome da instância WhatsApp' };

// Base params for chatbot create actions
const chatbotBaseParams = [
  instanceParam,
  { name: 'enabled', in: 'body' as const, type: 'boolean' as const, required: false, desc: 'Habilitar ou desabilitar o bot' },
  { name: 'description', in: 'body' as const, type: 'string' as const, required: true, desc: 'Descrição do bot' },
  { name: 'expire', in: 'body' as const, type: 'number' as const, required: false, desc: 'Tempo de expiração da sessão em segundos' },
  { name: 'keywordFinish', in: 'body' as const, type: 'string' as const, required: false, desc: 'Palavra-chave para encerrar sessão' },
  { name: 'delayMessage', in: 'body' as const, type: 'number' as const, required: false, desc: 'Delay entre mensagens em ms' },
  { name: 'unknownMessage', in: 'body' as const, type: 'string' as const, required: false, desc: 'Mensagem para inputs não reconhecidos' },
  { name: 'listeningFromMe', in: 'body' as const, type: 'boolean' as const, required: false, desc: 'Escutar mensagens enviadas por mim' },
  { name: 'stopBotFromMe', in: 'body' as const, type: 'boolean' as const, required: false, desc: 'Parar bot quando eu enviar mensagem' },
  { name: 'keepOpen', in: 'body' as const, type: 'boolean' as const, required: false, desc: 'Manter sessão aberta' },
  { name: 'debounceTime', in: 'body' as const, type: 'number' as const, required: false, desc: 'Tempo de debounce em ms' },
  { name: 'triggerType', in: 'body' as const, type: 'string' as const, required: true, desc: 'Tipo de trigger: all|keyword' },
  { name: 'triggerOperator', in: 'body' as const, type: 'string' as const, required: false, desc: 'Operador do trigger: contains|equals|startsWith|endsWith|regex' },
  { name: 'triggerValue', in: 'body' as const, type: 'string' as const, required: false, desc: 'Valor do trigger' },
  { name: 'ignoreJids', in: 'body' as const, type: 'array' as const, required: false, desc: 'Lista de JIDs a ignorar' },
];

const chatbotSettingsParams = [
  instanceParam,
  { name: 'expire', in: 'body' as const, type: 'number' as const, required: false, desc: 'Tempo de expiração em segundos' },
  { name: 'keywordFinish', in: 'body' as const, type: 'string' as const, required: false, desc: 'Palavra-chave para encerrar sessão' },
  { name: 'delayMessage', in: 'body' as const, type: 'number' as const, required: false, desc: 'Delay entre mensagens em ms' },
  { name: 'unknownMessage', in: 'body' as const, type: 'string' as const, required: false, desc: 'Mensagem para inputs não reconhecidos' },
  { name: 'listeningFromMe', in: 'body' as const, type: 'boolean' as const, required: false, desc: 'Escutar mensagens enviadas por mim' },
  { name: 'stopBotFromMe', in: 'body' as const, type: 'boolean' as const, required: false, desc: 'Parar bot quando eu enviar mensagem' },
  { name: 'keepOpen', in: 'body' as const, type: 'boolean' as const, required: false, desc: 'Manter sessão aberta' },
  { name: 'debounceTime', in: 'body' as const, type: 'number' as const, required: false, desc: 'Tempo de debounce em ms' },
  { name: 'ignoreJids', in: 'body' as const, type: 'array' as const, required: false, desc: 'Lista de JIDs a ignorar' },
  { name: 'splitMessages', in: 'body' as const, type: 'boolean' as const, required: false, desc: 'Dividir mensagens longas' },
  { name: 'timePerChar', in: 'body' as const, type: 'number' as const, required: false, desc: 'Tempo por caractere em ms' },
  { name: 'fallbackId', in: 'body' as const, type: 'string' as const, required: false, desc: 'ID do bot fallback' },
];

export const catalog: Action[] = [
  // ── INSTANCE ──────────────────────────────────────────────────────────────
  {
    id: 'instance.create',
    domain: 'instance',
    method: 'POST',
    path: '/instance/create',
    readOnly: false,
    summary: 'Cria uma nova instância WhatsApp',
    params: [
      { name: 'instanceName', in: 'body', type: 'string', required: true, desc: 'Nome único da instância' },
      { name: 'integration', in: 'body', type: 'string', required: false, desc: 'Tipo de integração: WHATSAPP-BAILEYS|WHATSAPP-BUSINESS|EVOLUTION' },
      { name: 'qrcode', in: 'body', type: 'boolean', required: false, desc: 'Gerar QR code ao criar' },
      { name: 'number', in: 'body', type: 'string', required: false, desc: 'Número do WhatsApp Business' },
      { name: 'token', in: 'body', type: 'string', required: false, desc: 'Token de autenticação da instância' },
    ],
  },
  {
    id: 'instance.restart',
    domain: 'instance',
    method: 'POST',
    path: '/instance/restart/:instance',
    readOnly: false,
    summary: 'Reinicia a instância WhatsApp',
    params: [instanceParam],
  },
  {
    id: 'instance.connect',
    domain: 'instance',
    method: 'GET',
    path: '/instance/connect/:instance',
    readOnly: true,
    summary: 'Conecta a instância e retorna QR code',
    params: [instanceParam],
  },
  {
    id: 'instance.connectionState',
    domain: 'instance',
    method: 'GET',
    path: '/instance/connectionState/:instance',
    readOnly: true,
    summary: 'Retorna o estado de conexão da instância',
    params: [instanceParam],
  },
  {
    id: 'instance.fetchInstances',
    domain: 'instance',
    method: 'GET',
    path: '/instance/fetchInstances',
    readOnly: true,
    summary: 'Lista todas as instâncias',
    params: [
      { name: 'instanceName', in: 'query', type: 'string', required: false, desc: 'Filtrar por nome da instância' },
    ],
  },
  {
    id: 'instance.setPresence',
    domain: 'instance',
    method: 'POST',
    path: '/instance/setPresence/:instance',
    readOnly: false,
    summary: 'Define o status de presença da instância',
    params: [
      instanceParam,
      { name: 'presence', in: 'body', type: 'string', required: true, desc: 'Status: available|unavailable|composing|recording|paused' },
    ],
  },
  {
    id: 'instance.logout',
    domain: 'instance',
    method: 'DELETE',
    path: '/instance/logout/:instance',
    readOnly: false,
    summary: 'Desconecta a instância do WhatsApp',
    params: [instanceParam],
  },
  {
    id: 'instance.delete',
    domain: 'instance',
    method: 'DELETE',
    path: '/instance/delete/:instance',
    readOnly: false,
    summary: 'Exclui permanentemente a instância',
    params: [instanceParam],
  },

  // ── MESSAGE ───────────────────────────────────────────────────────────────
  {
    id: 'message.sendText',
    domain: 'message',
    method: 'POST',
    path: '/message/sendText/:instance',
    readOnly: false,
    summary: 'Envia mensagem de texto',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI ex:5511999999999' },
      { name: 'text', in: 'body', type: 'string', required: true, desc: 'Conteúdo da mensagem' },
      { name: 'delay', in: 'body', type: 'number', required: false, desc: 'Delay antes de enviar em ms' },
      { name: 'linkPreview', in: 'body', type: 'boolean', required: false, desc: 'Habilitar preview de links' },
      { name: 'quoted', in: 'body', type: 'object', required: false, desc: 'Mensagem a ser citada' },
      { name: 'mentioned', in: 'body', type: 'array', required: false, desc: 'Lista de números a mencionar' },
    ],
  },
  {
    id: 'message.sendMedia',
    domain: 'message',
    method: 'POST',
    path: '/message/sendMedia/:instance',
    readOnly: false,
    summary: 'Envia mídia (imagem, documento, vídeo, áudio)',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'mediatype', in: 'body', type: 'string', required: true, desc: 'Tipo de mídia: image|document|video|audio|ptv' },
      { name: 'media', in: 'body', type: 'string', required: true, desc: 'URL ou base64 da mídia' },
      { name: 'caption', in: 'body', type: 'string', required: false, desc: 'Legenda da mídia' },
      { name: 'fileName', in: 'body', type: 'string', required: false, desc: 'Nome do arquivo' },
      { name: 'mimetype', in: 'body', type: 'string', required: false, desc: 'MIME type do arquivo' },
      { name: 'delay', in: 'body', type: 'number', required: false, desc: 'Delay antes de enviar em ms' },
    ],
  },
  {
    id: 'message.sendPtv',
    domain: 'message',
    method: 'POST',
    path: '/message/sendPtv/:instance',
    readOnly: false,
    summary: 'Envia vídeo PTV (picture-in-picture)',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'video', in: 'body', type: 'string', required: true, desc: 'URL ou base64 do vídeo' },
    ],
  },
  {
    id: 'message.sendWhatsAppAudio',
    domain: 'message',
    method: 'POST',
    path: '/message/sendWhatsAppAudio/:instance',
    readOnly: false,
    summary: 'Envia áudio no formato WhatsApp (PTT)',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'audio', in: 'body', type: 'string', required: true, desc: 'URL ou base64 do áudio' },
    ],
  },
  {
    id: 'message.sendSticker',
    domain: 'message',
    method: 'POST',
    path: '/message/sendSticker/:instance',
    readOnly: false,
    summary: 'Envia sticker',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'sticker', in: 'body', type: 'string', required: true, desc: 'URL ou base64 do sticker' },
    ],
  },
  {
    id: 'message.sendLocation',
    domain: 'message',
    method: 'POST',
    path: '/message/sendLocation/:instance',
    readOnly: false,
    summary: 'Envia localização',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'latitude', in: 'body', type: 'number', required: true, desc: 'Latitude da localização' },
      { name: 'longitude', in: 'body', type: 'number', required: true, desc: 'Longitude da localização' },
      { name: 'name', in: 'body', type: 'string', required: false, desc: 'Nome do local' },
      { name: 'address', in: 'body', type: 'string', required: false, desc: 'Endereço do local' },
    ],
  },
  {
    id: 'message.sendContact',
    domain: 'message',
    method: 'POST',
    path: '/message/sendContact/:instance',
    readOnly: false,
    summary: 'Envia contato(s)',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'contact', in: 'body', type: 'array', required: true, desc: 'Array de contatos: [{fullName,wuid,phoneNumber}]' },
    ],
  },
  {
    id: 'message.sendReaction',
    domain: 'message',
    method: 'POST',
    path: '/message/sendReaction/:instance',
    readOnly: false,
    summary: 'Envia reação a uma mensagem',
    params: [
      instanceParam,
      { name: 'key', in: 'body', type: 'object', required: true, desc: 'Chave da mensagem: {id,remoteJid,fromMe}' },
      { name: 'reaction', in: 'body', type: 'string', required: true, desc: 'Emoji ou string vazia para remover reação' },
    ],
  },
  {
    id: 'message.sendPoll',
    domain: 'message',
    method: 'POST',
    path: '/message/sendPoll/:instance',
    readOnly: false,
    summary: 'Envia enquete',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'name', in: 'body', type: 'string', required: true, desc: 'Título da enquete' },
      { name: 'selectableCount', in: 'body', type: 'number', required: true, desc: 'Número de opções selecionáveis' },
      { name: 'values', in: 'body', type: 'array', required: true, desc: 'Opções da enquete' },
    ],
  },
  {
    id: 'message.sendList',
    domain: 'message',
    method: 'POST',
    path: '/message/sendList/:instance',
    readOnly: false,
    summary: 'Envia mensagem com lista de opções',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'title', in: 'body', type: 'string', required: true, desc: 'Título da lista' },
      { name: 'buttonText', in: 'body', type: 'string', required: true, desc: 'Texto do botão de abertura' },
      { name: 'sections', in: 'body', type: 'array', required: true, desc: 'Seções: [{title,rows:[{title,description,rowId}]}]' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição da lista' },
      { name: 'footerText', in: 'body', type: 'string', required: false, desc: 'Rodapé da lista' },
    ],
  },
  {
    id: 'message.sendButtons',
    domain: 'message',
    method: 'POST',
    path: '/message/sendButtons/:instance',
    readOnly: false,
    summary: 'Envia mensagem com botões',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'title', in: 'body', type: 'string', required: true, desc: 'Título da mensagem' },
      { name: 'buttons', in: 'body', type: 'array', required: true, desc: 'Botões: [{type,displayText,...}]' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição da mensagem' },
      { name: 'footer', in: 'body', type: 'string', required: false, desc: 'Rodapé da mensagem' },
    ],
  },
  {
    id: 'message.sendTemplate',
    domain: 'message',
    method: 'POST',
    path: '/message/sendTemplate/:instance',
    readOnly: false,
    summary: 'Envia template de mensagem (WhatsApp Business)',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número destino com DDI' },
      { name: 'name', in: 'body', type: 'string', required: true, desc: 'Nome do template' },
      { name: 'language', in: 'body', type: 'string', required: true, desc: 'Idioma do template ex: pt_BR' },
      { name: 'components', in: 'body', type: 'array', required: true, desc: 'Componentes do template' },
    ],
  },
  {
    id: 'message.sendStatus',
    domain: 'message',
    method: 'POST',
    path: '/message/sendStatus/:instance',
    readOnly: false,
    summary: 'Envia status/story',
    params: [
      instanceParam,
      { name: 'type', in: 'body', type: 'string', required: true, desc: 'Tipo: text|image|video|audio' },
      { name: 'content', in: 'body', type: 'string', required: true, desc: 'Conteúdo do status' },
      { name: 'statusJidList', in: 'body', type: 'array', required: false, desc: 'Lista de JIDs para enviar o status' },
      { name: 'backgroundColor', in: 'body', type: 'string', required: false, desc: 'Cor de fundo (hex)' },
      { name: 'font', in: 'body', type: 'number', required: false, desc: 'Fonte do texto' },
    ],
  },

  // ── CHAT ──────────────────────────────────────────────────────────────────
  {
    id: 'chat.whatsappNumbers',
    domain: 'chat',
    method: 'POST',
    path: '/chat/whatsappNumbers/:instance',
    readOnly: true,
    summary: 'Verifica quais números têm WhatsApp',
    params: [
      instanceParam,
      { name: 'numbers', in: 'body', type: 'array', required: true, desc: 'Lista de números a verificar' },
    ],
  },
  {
    id: 'chat.markMessageAsRead',
    domain: 'chat',
    method: 'POST',
    path: '/chat/markMessageAsRead/:instance',
    readOnly: false,
    summary: 'Marca mensagens como lidas',
    params: [
      instanceParam,
      { name: 'readMessages', in: 'body', type: 'array', required: true, desc: 'Mensagens a marcar: [{id,remoteJid,fromMe}]' },
    ],
  },
  {
    id: 'chat.archiveChat',
    domain: 'chat',
    method: 'POST',
    path: '/chat/archiveChat/:instance',
    readOnly: false,
    summary: 'Arquiva ou desarquiva uma conversa',
    params: [
      instanceParam,
      { name: 'lastMessage', in: 'body', type: 'object', required: true, desc: 'Última mensagem da conversa' },
      { name: 'archive', in: 'body', type: 'boolean', required: true, desc: 'true para arquivar, false para desarquivar' },
    ],
  },
  {
    id: 'chat.markChatUnread',
    domain: 'chat',
    method: 'POST',
    path: '/chat/markChatUnread/:instance',
    readOnly: false,
    summary: 'Marca uma conversa como não lida',
    params: [
      instanceParam,
      { name: 'lastMessage', in: 'body', type: 'object', required: true, desc: 'Última mensagem da conversa' },
    ],
  },
  {
    id: 'chat.deleteMessageForEveryone',
    domain: 'chat',
    method: 'DELETE',
    path: '/chat/deleteMessageForEveryone/:instance',
    readOnly: false,
    summary: 'Apaga mensagem para todos',
    params: [
      instanceParam,
      { name: 'id', in: 'body', type: 'string', required: true, desc: 'ID da mensagem' },
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID do destinatário' },
      { name: 'fromMe', in: 'body', type: 'boolean', required: true, desc: 'Se a mensagem foi enviada por mim' },
      { name: 'participant', in: 'body', type: 'string', required: false, desc: 'Participante (em grupos)' },
    ],
  },
  {
    id: 'chat.fetchProfilePictureUrl',
    domain: 'chat',
    method: 'POST',
    path: '/chat/fetchProfilePictureUrl/:instance',
    readOnly: true,
    summary: 'Obtém URL da foto de perfil',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número do contato' },
    ],
  },
  {
    id: 'chat.getBase64FromMediaMessage',
    domain: 'chat',
    method: 'POST',
    path: '/chat/getBase64FromMediaMessage/:instance',
    readOnly: true,
    summary: 'Converte mídia de mensagem para base64',
    params: [
      instanceParam,
      { name: 'message', in: 'body', type: 'object', required: true, desc: 'Objeto da mensagem com mídia' },
      { name: 'convertToMp4', in: 'body', type: 'boolean', required: false, desc: 'Converter áudio para MP4' },
    ],
  },
  {
    id: 'chat.updateMessage',
    domain: 'chat',
    method: 'POST',
    path: '/chat/updateMessage/:instance',
    readOnly: false,
    summary: 'Edita uma mensagem enviada',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número do destinatário' },
      { name: 'key', in: 'body', type: 'object', required: true, desc: 'Chave da mensagem a editar' },
      { name: 'text', in: 'body', type: 'string', required: true, desc: 'Novo texto da mensagem' },
    ],
  },
  {
    id: 'chat.sendPresence',
    domain: 'chat',
    method: 'POST',
    path: '/chat/sendPresence/:instance',
    readOnly: false,
    summary: 'Envia indicador de presença (digitando, gravando)',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número do destinatário' },
      { name: 'options', in: 'body', type: 'object', required: true, desc: 'Opções de presença: {presence: composing|recording|paused}' },
    ],
  },
  {
    id: 'chat.updateBlockStatus',
    domain: 'chat',
    method: 'POST',
    path: '/chat/updateBlockStatus/:instance',
    readOnly: false,
    summary: 'Bloqueia ou desbloqueia um contato',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número do contato' },
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Ação: block|unblock' },
    ],
  },
  {
    id: 'chat.findContacts',
    domain: 'chat',
    method: 'POST',
    path: '/chat/findContacts/:instance',
    readOnly: true,
    summary: 'Busca contatos da instância',
    params: [
      instanceParam,
      { name: 'where', in: 'body', type: 'object', required: false, desc: 'Filtros de busca' },
    ],
  },
  {
    id: 'chat.findMessages',
    domain: 'chat',
    method: 'POST',
    path: '/chat/findMessages/:instance',
    readOnly: true,
    summary: 'Busca mensagens da instância',
    params: [
      instanceParam,
      { name: 'where', in: 'body', type: 'object', required: false, desc: 'Filtros de busca' },
      { name: 'limit', in: 'body', type: 'number', required: false, desc: 'Limite de resultados' },
      { name: 'offset', in: 'body', type: 'number', required: false, desc: 'Offset para paginação' },
    ],
  },
  {
    id: 'chat.findStatusMessage',
    domain: 'chat',
    method: 'POST',
    path: '/chat/findStatusMessage/:instance',
    readOnly: true,
    summary: 'Busca mensagens de status',
    params: [
      instanceParam,
      { name: 'where', in: 'body', type: 'object', required: false, desc: 'Filtros de busca' },
    ],
  },
  {
    id: 'chat.findChats',
    domain: 'chat',
    method: 'POST',
    path: '/chat/findChats/:instance',
    readOnly: true,
    summary: 'Busca conversas da instância',
    params: [
      instanceParam,
      { name: 'where', in: 'body', type: 'object', required: false, desc: 'Filtros de busca' },
    ],
  },
  {
    id: 'chat.findChatByRemoteJid',
    domain: 'chat',
    method: 'GET',
    path: '/chat/findChatByRemoteJid/:instance',
    readOnly: true,
    summary: 'Busca conversa por JID',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'query', type: 'string', required: true, desc: 'JID do contato ou grupo' },
    ],
  },
  {
    id: 'chat.fetchBusinessProfile',
    domain: 'chat',
    method: 'POST',
    path: '/chat/fetchBusinessProfile/:instance',
    readOnly: true,
    summary: 'Obtém perfil comercial de um número',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número do contato' },
    ],
  },
  {
    id: 'chat.fetchProfile',
    domain: 'chat',
    method: 'POST',
    path: '/chat/fetchProfile/:instance',
    readOnly: true,
    summary: 'Obtém perfil de um número',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número do contato' },
    ],
  },
  {
    id: 'chat.updateProfileName',
    domain: 'chat',
    method: 'POST',
    path: '/chat/updateProfileName/:instance',
    readOnly: false,
    summary: 'Atualiza nome do perfil da instância',
    params: [
      instanceParam,
      { name: 'name', in: 'body', type: 'string', required: true, desc: 'Novo nome do perfil' },
    ],
  },
  {
    id: 'chat.updateProfileStatus',
    domain: 'chat',
    method: 'POST',
    path: '/chat/updateProfileStatus/:instance',
    readOnly: false,
    summary: 'Atualiza status do perfil da instância',
    params: [
      instanceParam,
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Novo status do perfil' },
    ],
  },
  {
    id: 'chat.updateProfilePicture',
    domain: 'chat',
    method: 'POST',
    path: '/chat/updateProfilePicture/:instance',
    readOnly: false,
    summary: 'Atualiza foto do perfil da instância',
    params: [
      instanceParam,
      { name: 'picture', in: 'body', type: 'string', required: true, desc: 'URL da imagem' },
    ],
  },
  {
    id: 'chat.removeProfilePicture',
    domain: 'chat',
    method: 'DELETE',
    path: '/chat/removeProfilePicture/:instance',
    readOnly: false,
    summary: 'Remove foto do perfil da instância',
    params: [instanceParam],
  },
  {
    id: 'chat.fetchPrivacySettings',
    domain: 'chat',
    method: 'GET',
    path: '/chat/fetchPrivacySettings/:instance',
    readOnly: true,
    summary: 'Obtém configurações de privacidade',
    params: [instanceParam],
  },
  {
    id: 'chat.updatePrivacySettings',
    domain: 'chat',
    method: 'POST',
    path: '/chat/updatePrivacySettings/:instance',
    readOnly: false,
    summary: 'Atualiza configurações de privacidade',
    params: [
      instanceParam,
      { name: 'readreceipts', in: 'body', type: 'string', required: false, desc: 'Confirmação de leitura: all|none' },
      { name: 'profile', in: 'body', type: 'string', required: false, desc: 'Visibilidade do perfil' },
      { name: 'status', in: 'body', type: 'string', required: false, desc: 'Visibilidade do status' },
      { name: 'online', in: 'body', type: 'string', required: false, desc: 'Visibilidade do online' },
      { name: 'last', in: 'body', type: 'string', required: false, desc: 'Visibilidade do último acesso' },
      { name: 'groupadd', in: 'body', type: 'string', required: false, desc: 'Quem pode adicionar a grupos' },
    ],
  },

  // ── GROUP ─────────────────────────────────────────────────────────────────
  {
    id: 'group.create',
    domain: 'group',
    method: 'POST',
    path: '/group/create/:instance',
    readOnly: false,
    summary: 'Cria um novo grupo',
    params: [
      instanceParam,
      { name: 'subject', in: 'body', type: 'string', required: true, desc: 'Nome do grupo' },
      { name: 'participants', in: 'body', type: 'array', required: true, desc: 'Lista de participantes' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição do grupo' },
    ],
  },
  {
    id: 'group.updateGroupSubject',
    domain: 'group',
    method: 'POST',
    path: '/group/updateGroupSubject/:instance',
    readOnly: false,
    summary: 'Atualiza o nome do grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
      { name: 'subject', in: 'body', type: 'string', required: true, desc: 'Novo nome do grupo' },
    ],
  },
  {
    id: 'group.updateGroupPicture',
    domain: 'group',
    method: 'POST',
    path: '/group/updateGroupPicture/:instance',
    readOnly: false,
    summary: 'Atualiza a foto do grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
      { name: 'image', in: 'body', type: 'string', required: true, desc: 'URL da imagem' },
    ],
  },
  {
    id: 'group.updateGroupDescription',
    domain: 'group',
    method: 'POST',
    path: '/group/updateGroupDescription/:instance',
    readOnly: false,
    summary: 'Atualiza a descrição do grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
      { name: 'description', in: 'body', type: 'string', required: true, desc: 'Nova descrição do grupo' },
    ],
  },
  {
    id: 'group.findGroupInfos',
    domain: 'group',
    method: 'GET',
    path: '/group/findGroupInfos/:instance',
    readOnly: true,
    summary: 'Obtém informações de um grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'query', type: 'string', required: true, desc: 'JID do grupo' },
    ],
  },
  {
    id: 'group.fetchAllGroups',
    domain: 'group',
    method: 'GET',
    path: '/group/fetchAllGroups/:instance',
    readOnly: true,
    summary: 'Lista todos os grupos da instância',
    params: [
      instanceParam,
      { name: 'getParticipants', in: 'query', type: 'string', required: false, desc: 'Incluir participantes: true|false' },
    ],
  },
  {
    id: 'group.participants',
    domain: 'group',
    method: 'GET',
    path: '/group/participants/:instance',
    readOnly: true,
    summary: 'Lista participantes de um grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'query', type: 'string', required: true, desc: 'JID do grupo' },
    ],
  },
  {
    id: 'group.inviteCode',
    domain: 'group',
    method: 'GET',
    path: '/group/inviteCode/:instance',
    readOnly: true,
    summary: 'Obtém link de convite do grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'query', type: 'string', required: true, desc: 'JID do grupo' },
    ],
  },
  {
    id: 'group.inviteInfo',
    domain: 'group',
    method: 'GET',
    path: '/group/inviteInfo/:instance',
    readOnly: true,
    summary: 'Obtém informações de um link de convite',
    params: [
      instanceParam,
      { name: 'inviteCode', in: 'query', type: 'string', required: true, desc: 'Código do convite' },
    ],
  },
  {
    id: 'group.acceptInviteCode',
    domain: 'group',
    method: 'GET',
    path: '/group/acceptInviteCode/:instance',
    readOnly: false,
    summary: 'Aceita um convite de grupo',
    params: [
      instanceParam,
      { name: 'inviteCode', in: 'query', type: 'string', required: true, desc: 'Código do convite' },
    ],
  },
  {
    id: 'group.sendInvite',
    domain: 'group',
    method: 'POST',
    path: '/group/sendInvite/:instance',
    readOnly: false,
    summary: 'Envia convite de grupo para contatos',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
      { name: 'description', in: 'body', type: 'string', required: true, desc: 'Mensagem do convite' },
      { name: 'numbers', in: 'body', type: 'array', required: true, desc: 'Lista de números a convidar' },
    ],
  },
  {
    id: 'group.revokeInviteCode',
    domain: 'group',
    method: 'POST',
    path: '/group/revokeInviteCode/:instance',
    readOnly: false,
    summary: 'Revoga o link de convite do grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
    ],
  },
  {
    id: 'group.updateParticipant',
    domain: 'group',
    method: 'POST',
    path: '/group/updateParticipant/:instance',
    readOnly: false,
    summary: 'Gerencia participantes do grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove|promote|demote' },
      { name: 'participants', in: 'body', type: 'array', required: true, desc: 'Lista de participantes' },
    ],
  },
  {
    id: 'group.updateSetting',
    domain: 'group',
    method: 'POST',
    path: '/group/updateSetting/:instance',
    readOnly: false,
    summary: 'Atualiza configurações do grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Configuração: announcement|not_announcement|unlocked|locked' },
    ],
  },
  {
    id: 'group.toggleEphemeral',
    domain: 'group',
    method: 'POST',
    path: '/group/toggleEphemeral/:instance',
    readOnly: false,
    summary: 'Configura mensagens temporárias no grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
      { name: 'expiration', in: 'body', type: 'number', required: true, desc: 'Duração em segundos: 0|86400|604800|7776000' },
    ],
  },
  {
    id: 'group.leaveGroup',
    domain: 'group',
    method: 'DELETE',
    path: '/group/leaveGroup/:instance',
    readOnly: false,
    summary: 'Sai de um grupo',
    params: [
      instanceParam,
      { name: 'groupJid', in: 'body', type: 'string', required: true, desc: 'JID do grupo' },
    ],
  },

  // ── CALL ──────────────────────────────────────────────────────────────────
  {
    id: 'call.offer',
    domain: 'call',
    method: 'POST',
    path: '/call/offer/:instance',
    readOnly: false,
    summary: 'Inicia uma chamada de voz ou vídeo',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número a chamar' },
      { name: 'isVideo', in: 'body', type: 'boolean', required: false, desc: 'Chamada de vídeo' },
      { name: 'callDuration', in: 'body', type: 'number', required: false, desc: 'Duração da chamada em segundos' },
    ],
  },

  // ── SETTINGS ──────────────────────────────────────────────────────────────
  {
    id: 'settings.set',
    domain: 'settings',
    method: 'POST',
    path: '/settings/set/:instance',
    readOnly: false,
    summary: 'Define configurações da instância',
    params: [
      instanceParam,
      { name: 'rejectCall', in: 'body', type: 'boolean', required: false, desc: 'Rejeitar chamadas automaticamente' },
      { name: 'msgCall', in: 'body', type: 'string', required: false, desc: 'Mensagem ao rejeitar chamada' },
      { name: 'groupsIgnore', in: 'body', type: 'boolean', required: false, desc: 'Ignorar mensagens de grupos' },
      { name: 'alwaysOnline', in: 'body', type: 'boolean', required: false, desc: 'Manter sempre online' },
      { name: 'readMessages', in: 'body', type: 'boolean', required: false, desc: 'Marcar mensagens como lidas automaticamente' },
      { name: 'readStatus', in: 'body', type: 'boolean', required: false, desc: 'Marcar status como visualizado automaticamente' },
      { name: 'syncFullHistory', in: 'body', type: 'boolean', required: false, desc: 'Sincronizar histórico completo' },
    ],
  },
  {
    id: 'settings.find',
    domain: 'settings',
    method: 'GET',
    path: '/settings/find/:instance',
    readOnly: true,
    summary: 'Obtém configurações da instância',
    params: [instanceParam],
  },

  // ── LABEL ─────────────────────────────────────────────────────────────────
  {
    id: 'label.findLabels',
    domain: 'label',
    method: 'GET',
    path: '/label/findLabels/:instance',
    readOnly: true,
    summary: 'Lista etiquetas disponíveis',
    params: [instanceParam],
  },
  {
    id: 'label.handleLabel',
    domain: 'label',
    method: 'POST',
    path: '/label/handleLabel/:instance',
    readOnly: false,
    summary: 'Adiciona ou remove etiqueta de uma conversa',
    params: [
      instanceParam,
      { name: 'number', in: 'body', type: 'string', required: true, desc: 'Número do contato' },
      { name: 'labelId', in: 'body', type: 'string', required: true, desc: 'ID da etiqueta' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove' },
    ],
  },

  // ── PROXY ─────────────────────────────────────────────────────────────────
  {
    id: 'proxy.set',
    domain: 'proxy',
    method: 'POST',
    path: '/proxy/set/:instance',
    readOnly: false,
    summary: 'Configura proxy para a instância',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar proxy' },
      { name: 'host', in: 'body', type: 'string', required: true, desc: 'Host do proxy' },
      { name: 'port', in: 'body', type: 'string', required: true, desc: 'Porta do proxy' },
      { name: 'protocol', in: 'body', type: 'string', required: true, desc: 'Protocolo: http|https|socks4|socks5' },
      { name: 'username', in: 'body', type: 'string', required: false, desc: 'Usuário do proxy' },
      { name: 'password', in: 'body', type: 'string', required: false, desc: 'Senha do proxy' },
    ],
  },
  {
    id: 'proxy.find',
    domain: 'proxy',
    method: 'GET',
    path: '/proxy/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração de proxy da instância',
    params: [instanceParam],
  },

  // ── EVENTS ────────────────────────────────────────────────────────────────
  // webhook
  {
    id: 'event.webhook.set',
    domain: 'event',
    method: 'POST',
    path: '/webhook/set/:instance',
    readOnly: false,
    summary: 'Configura webhook da instância',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar webhook' },
      { name: 'url', in: 'body', type: 'string', required: true, desc: 'URL do webhook' },
      { name: 'byEvents', in: 'body', type: 'boolean', required: false, desc: 'Enviar por evento específico' },
      { name: 'base64', in: 'body', type: 'boolean', required: false, desc: 'Enviar mídia em base64' },
      { name: 'headers', in: 'body', type: 'object', required: false, desc: 'Headers HTTP adicionais' },
      { name: 'events', in: 'body', type: 'array', required: false, desc: 'Lista de eventos a escutar' },
    ],
  },
  {
    id: 'event.webhook.find',
    domain: 'event',
    method: 'GET',
    path: '/webhook/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração de webhook da instância',
    params: [instanceParam],
  },
  // websocket
  {
    id: 'event.websocket.set',
    domain: 'event',
    method: 'POST',
    path: '/websocket/set/:instance',
    readOnly: false,
    summary: 'Configura WebSocket da instância',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar WebSocket' },
      { name: 'events', in: 'body', type: 'array', required: false, desc: 'Lista de eventos a escutar' },
    ],
  },
  {
    id: 'event.websocket.find',
    domain: 'event',
    method: 'GET',
    path: '/websocket/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração de WebSocket da instância',
    params: [instanceParam],
  },
  // rabbitmq
  {
    id: 'event.rabbitmq.set',
    domain: 'event',
    method: 'POST',
    path: '/rabbitmq/set/:instance',
    readOnly: false,
    summary: 'Configura RabbitMQ da instância',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar RabbitMQ' },
      { name: 'events', in: 'body', type: 'array', required: false, desc: 'Lista de eventos a escutar' },
    ],
  },
  {
    id: 'event.rabbitmq.find',
    domain: 'event',
    method: 'GET',
    path: '/rabbitmq/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração de RabbitMQ da instância',
    params: [instanceParam],
  },
  // nats
  {
    id: 'event.nats.set',
    domain: 'event',
    method: 'POST',
    path: '/nats/set/:instance',
    readOnly: false,
    summary: 'Configura NATS da instância',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar NATS' },
      { name: 'events', in: 'body', type: 'array', required: false, desc: 'Lista de eventos a escutar' },
    ],
  },
  {
    id: 'event.nats.find',
    domain: 'event',
    method: 'GET',
    path: '/nats/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração de NATS da instância',
    params: [instanceParam],
  },
  // pusher
  {
    id: 'event.pusher.set',
    domain: 'event',
    method: 'POST',
    path: '/pusher/set/:instance',
    readOnly: false,
    summary: 'Configura Pusher da instância',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar Pusher' },
      { name: 'events', in: 'body', type: 'array', required: false, desc: 'Lista de eventos a escutar' },
    ],
  },
  {
    id: 'event.pusher.find',
    domain: 'event',
    method: 'GET',
    path: '/pusher/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração de Pusher da instância',
    params: [instanceParam],
  },
  // sqs
  {
    id: 'event.sqs.set',
    domain: 'event',
    method: 'POST',
    path: '/sqs/set/:instance',
    readOnly: false,
    summary: 'Configura Amazon SQS da instância',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar SQS' },
      { name: 'events', in: 'body', type: 'array', required: false, desc: 'Lista de eventos a escutar' },
    ],
  },
  {
    id: 'event.sqs.find',
    domain: 'event',
    method: 'GET',
    path: '/sqs/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração de SQS da instância',
    params: [instanceParam],
  },
  // kafka
  {
    id: 'event.kafka.set',
    domain: 'event',
    method: 'POST',
    path: '/kafka/set/:instance',
    readOnly: false,
    summary: 'Configura Kafka da instância',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar Kafka' },
      { name: 'events', in: 'body', type: 'array', required: false, desc: 'Lista de eventos a escutar' },
    ],
  },
  {
    id: 'event.kafka.find',
    domain: 'event',
    method: 'GET',
    path: '/kafka/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração de Kafka da instância',
    params: [instanceParam],
  },

  // ── CHATBOT — CHATWOOT ────────────────────────────────────────────────────
  {
    id: 'chatbot.chatwoot.set',
    domain: 'chatbot',
    method: 'POST',
    path: '/chatwoot/set/:instance',
    readOnly: false,
    summary: 'Configura integração com Chatwoot',
    params: [
      instanceParam,
      { name: 'enabled', in: 'body', type: 'boolean', required: true, desc: 'Habilitar Chatwoot' },
      { name: 'accountId', in: 'body', type: 'string', required: true, desc: 'ID da conta Chatwoot' },
      { name: 'token', in: 'body', type: 'string', required: true, desc: 'Token de acesso Chatwoot' },
      { name: 'url', in: 'body', type: 'string', required: true, desc: 'URL da instância Chatwoot' },
      { name: 'signMsg', in: 'body', type: 'boolean', required: false, desc: 'Assinar mensagens' },
      { name: 'reopenConversation', in: 'body', type: 'boolean', required: false, desc: 'Reabrir conversa existente' },
      { name: 'conversationPending', in: 'body', type: 'boolean', required: false, desc: 'Criar conversa como pendente' },
      { name: 'nameInbox', in: 'body', type: 'string', required: false, desc: 'Nome da caixa de entrada' },
      { name: 'mergeBrazilContacts', in: 'body', type: 'boolean', required: false, desc: 'Mesclar contatos brasileiros' },
      { name: 'importContacts', in: 'body', type: 'boolean', required: false, desc: 'Importar contatos' },
      { name: 'importMessages', in: 'body', type: 'boolean', required: false, desc: 'Importar mensagens' },
      { name: 'daysLimitImportMessages', in: 'body', type: 'number', required: false, desc: 'Dias limite para importação de mensagens' },
      { name: 'autoCreate', in: 'body', type: 'boolean', required: false, desc: 'Criar conversa automaticamente' },
      { name: 'organization', in: 'body', type: 'string', required: false, desc: 'Organização do Chatwoot' },
      { name: 'logo', in: 'body', type: 'string', required: false, desc: 'URL do logo' },
    ],
  },
  {
    id: 'chatbot.chatwoot.find',
    domain: 'chatbot',
    method: 'GET',
    path: '/chatwoot/find/:instance',
    readOnly: true,
    summary: 'Obtém configuração do Chatwoot',
    params: [instanceParam],
  },

  // ── CHATBOT — EVOLUTIONBOT ────────────────────────────────────────────────
  {
    id: 'chatbot.evolutionBot.create',
    domain: 'chatbot',
    method: 'POST',
    path: '/evolutionBot/create/:instance',
    readOnly: false,
    summary: 'Cria um bot EvolutionBot',
    params: chatbotBaseParams,
  },
  {
    id: 'chatbot.evolutionBot.find',
    domain: 'chatbot',
    method: 'GET',
    path: '/evolutionBot/find/:instance',
    readOnly: true,
    summary: 'Lista bots EvolutionBot da instância',
    params: [instanceParam],
  },
  {
    id: 'chatbot.evolutionBot.fetch',
    domain: 'chatbot',
    method: 'GET',
    path: '/evolutionBot/fetch/:evolutionBotId/:instance',
    readOnly: true,
    summary: 'Obtém detalhes de um bot EvolutionBot',
    params: [
      instanceParam,
      { name: 'evolutionBotId', in: 'path', type: 'string', required: true, desc: 'ID do bot EvolutionBot' },
    ],
  },
  {
    id: 'chatbot.evolutionBot.update',
    domain: 'chatbot',
    method: 'PUT',
    path: '/evolutionBot/update/:evolutionBotId/:instance',
    readOnly: false,
    summary: 'Atualiza um bot EvolutionBot',
    params: [
      instanceParam,
      { name: 'evolutionBotId', in: 'path', type: 'string', required: true, desc: 'ID do bot EvolutionBot' },
      { name: 'enabled', in: 'body', type: 'boolean', required: false, desc: 'Habilitar ou desabilitar o bot' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição do bot' },
      { name: 'expire', in: 'body', type: 'number', required: false, desc: 'Tempo de expiração em segundos' },
      { name: 'keywordFinish', in: 'body', type: 'string', required: false, desc: 'Palavra-chave para encerrar sessão' },
      { name: 'delayMessage', in: 'body', type: 'number', required: false, desc: 'Delay entre mensagens em ms' },
      { name: 'unknownMessage', in: 'body', type: 'string', required: false, desc: 'Mensagem para inputs não reconhecidos' },
      { name: 'listeningFromMe', in: 'body', type: 'boolean', required: false, desc: 'Escutar mensagens enviadas por mim' },
      { name: 'stopBotFromMe', in: 'body', type: 'boolean', required: false, desc: 'Parar bot quando eu enviar mensagem' },
      { name: 'keepOpen', in: 'body', type: 'boolean', required: false, desc: 'Manter sessão aberta' },
      { name: 'debounceTime', in: 'body', type: 'number', required: false, desc: 'Tempo de debounce em ms' },
      { name: 'triggerType', in: 'body', type: 'string', required: false, desc: 'Tipo de trigger: all|keyword' },
      { name: 'triggerOperator', in: 'body', type: 'string', required: false, desc: 'Operador do trigger' },
      { name: 'triggerValue', in: 'body', type: 'string', required: false, desc: 'Valor do trigger' },
      { name: 'ignoreJids', in: 'body', type: 'array', required: false, desc: 'Lista de JIDs a ignorar' },
    ],
  },
  {
    id: 'chatbot.evolutionBot.delete',
    domain: 'chatbot',
    method: 'DELETE',
    path: '/evolutionBot/delete/:evolutionBotId/:instance',
    readOnly: false,
    summary: 'Exclui um bot EvolutionBot',
    params: [
      instanceParam,
      { name: 'evolutionBotId', in: 'path', type: 'string', required: true, desc: 'ID do bot EvolutionBot' },
    ],
  },
  {
    id: 'chatbot.evolutionBot.settings',
    domain: 'chatbot',
    method: 'POST',
    path: '/evolutionBot/settings/:instance',
    readOnly: false,
    summary: 'Define configurações globais do EvolutionBot',
    params: chatbotSettingsParams,
  },
  {
    id: 'chatbot.evolutionBot.fetchSettings',
    domain: 'chatbot',
    method: 'GET',
    path: '/evolutionBot/fetchSettings/:instance',
    readOnly: true,
    summary: 'Obtém configurações globais do EvolutionBot',
    params: [instanceParam],
  },
  {
    id: 'chatbot.evolutionBot.changeStatus',
    domain: 'chatbot',
    method: 'POST',
    path: '/evolutionBot/changeStatus/:instance',
    readOnly: false,
    summary: 'Altera status de uma sessão do EvolutionBot',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID da conversa' },
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Novo status: opened|closed|paused' },
    ],
  },
  {
    id: 'chatbot.evolutionBot.fetchSessions',
    domain: 'chatbot',
    method: 'GET',
    path: '/evolutionBot/fetchSessions/:evolutionBotId/:instance',
    readOnly: true,
    summary: 'Lista sessões ativas do EvolutionBot',
    params: [
      instanceParam,
      { name: 'evolutionBotId', in: 'path', type: 'string', required: true, desc: 'ID do bot EvolutionBot' },
    ],
  },
  {
    id: 'chatbot.evolutionBot.ignoreJid',
    domain: 'chatbot',
    method: 'POST',
    path: '/evolutionBot/ignoreJid/:instance',
    readOnly: false,
    summary: 'Adiciona ou remove JID da lista de ignorados do EvolutionBot',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID a ignorar/remover' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove' },
    ],
  },

  // ── CHATBOT — TYPEBOT ─────────────────────────────────────────────────────
  {
    id: 'chatbot.typebot.create',
    domain: 'chatbot',
    method: 'POST',
    path: '/typebot/create/:instance',
    readOnly: false,
    summary: 'Cria um bot Typebot',
    params: [
      ...chatbotBaseParams,
      { name: 'url', in: 'body', type: 'string', required: true, desc: 'URL do Typebot' },
      { name: 'typebot', in: 'body', type: 'string', required: true, desc: 'Nome do fluxo Typebot' },
    ],
  },
  {
    id: 'chatbot.typebot.find',
    domain: 'chatbot',
    method: 'GET',
    path: '/typebot/find/:instance',
    readOnly: true,
    summary: 'Lista bots Typebot da instância',
    params: [instanceParam],
  },
  {
    id: 'chatbot.typebot.fetch',
    domain: 'chatbot',
    method: 'GET',
    path: '/typebot/fetch/:typebotId/:instance',
    readOnly: true,
    summary: 'Obtém detalhes de um bot Typebot',
    params: [
      instanceParam,
      { name: 'typebotId', in: 'path', type: 'string', required: true, desc: 'ID do bot Typebot' },
    ],
  },
  {
    id: 'chatbot.typebot.update',
    domain: 'chatbot',
    method: 'PUT',
    path: '/typebot/update/:typebotId/:instance',
    readOnly: false,
    summary: 'Atualiza um bot Typebot',
    params: [
      instanceParam,
      { name: 'typebotId', in: 'path', type: 'string', required: true, desc: 'ID do bot Typebot' },
      { name: 'enabled', in: 'body', type: 'boolean', required: false, desc: 'Habilitar ou desabilitar' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição' },
      { name: 'url', in: 'body', type: 'string', required: false, desc: 'URL do Typebot' },
      { name: 'typebot', in: 'body', type: 'string', required: false, desc: 'Nome do fluxo' },
      { name: 'expire', in: 'body', type: 'number', required: false, desc: 'Tempo de expiração em segundos' },
      { name: 'keywordFinish', in: 'body', type: 'string', required: false, desc: 'Palavra-chave para encerrar' },
      { name: 'delayMessage', in: 'body', type: 'number', required: false, desc: 'Delay entre mensagens' },
      { name: 'unknownMessage', in: 'body', type: 'string', required: false, desc: 'Mensagem desconhecida' },
      { name: 'listeningFromMe', in: 'body', type: 'boolean', required: false, desc: 'Escutar minhas mensagens' },
      { name: 'stopBotFromMe', in: 'body', type: 'boolean', required: false, desc: 'Parar bot com minha mensagem' },
      { name: 'keepOpen', in: 'body', type: 'boolean', required: false, desc: 'Manter sessão aberta' },
      { name: 'debounceTime', in: 'body', type: 'number', required: false, desc: 'Tempo de debounce' },
      { name: 'triggerType', in: 'body', type: 'string', required: false, desc: 'Tipo de trigger' },
      { name: 'triggerOperator', in: 'body', type: 'string', required: false, desc: 'Operador do trigger' },
      { name: 'triggerValue', in: 'body', type: 'string', required: false, desc: 'Valor do trigger' },
      { name: 'ignoreJids', in: 'body', type: 'array', required: false, desc: 'JIDs a ignorar' },
    ],
  },
  {
    id: 'chatbot.typebot.delete',
    domain: 'chatbot',
    method: 'DELETE',
    path: '/typebot/delete/:typebotId/:instance',
    readOnly: false,
    summary: 'Exclui um bot Typebot',
    params: [
      instanceParam,
      { name: 'typebotId', in: 'path', type: 'string', required: true, desc: 'ID do bot Typebot' },
    ],
  },
  {
    id: 'chatbot.typebot.settings',
    domain: 'chatbot',
    method: 'POST',
    path: '/typebot/settings/:instance',
    readOnly: false,
    summary: 'Define configurações globais do Typebot',
    params: chatbotSettingsParams,
  },
  {
    id: 'chatbot.typebot.fetchSettings',
    domain: 'chatbot',
    method: 'GET',
    path: '/typebot/fetchSettings/:instance',
    readOnly: true,
    summary: 'Obtém configurações globais do Typebot',
    params: [instanceParam],
  },
  {
    id: 'chatbot.typebot.start',
    domain: 'chatbot',
    method: 'POST',
    path: '/typebot/start/:instance',
    readOnly: false,
    summary: 'Inicia sessão Typebot manualmente',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID do contato' },
      { name: 'url', in: 'body', type: 'string', required: true, desc: 'URL do Typebot' },
      { name: 'typebot', in: 'body', type: 'string', required: true, desc: 'Nome do fluxo Typebot' },
      { name: 'startSession', in: 'body', type: 'boolean', required: false, desc: 'Iniciar nova sessão' },
      { name: 'variables', in: 'body', type: 'array', required: false, desc: 'Variáveis iniciais' },
    ],
  },
  {
    id: 'chatbot.typebot.changeStatus',
    domain: 'chatbot',
    method: 'POST',
    path: '/typebot/changeStatus/:instance',
    readOnly: false,
    summary: 'Altera status de uma sessão Typebot',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID da conversa' },
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Novo status: opened|closed|paused' },
    ],
  },
  {
    id: 'chatbot.typebot.fetchSessions',
    domain: 'chatbot',
    method: 'GET',
    path: '/typebot/fetchSessions/:typebotId/:instance',
    readOnly: true,
    summary: 'Lista sessões ativas do Typebot',
    params: [
      instanceParam,
      { name: 'typebotId', in: 'path', type: 'string', required: true, desc: 'ID do bot Typebot' },
    ],
  },
  {
    id: 'chatbot.typebot.ignoreJid',
    domain: 'chatbot',
    method: 'POST',
    path: '/typebot/ignoreJid/:instance',
    readOnly: false,
    summary: 'Adiciona ou remove JID da lista de ignorados do Typebot',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID a ignorar/remover' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove' },
    ],
  },

  // ── CHATBOT — OPENAI ──────────────────────────────────────────────────────
  {
    id: 'chatbot.openai.createCreds',
    domain: 'chatbot',
    method: 'POST',
    path: '/openai/creds/:instance',
    readOnly: false,
    summary: 'Cria credenciais OpenAI',
    params: [
      instanceParam,
      { name: 'name', in: 'body', type: 'string', required: true, desc: 'Nome das credenciais' },
      { name: 'apiKey', in: 'body', type: 'string', required: true, desc: 'API Key da OpenAI' },
    ],
  },
  {
    id: 'chatbot.openai.findCreds',
    domain: 'chatbot',
    method: 'GET',
    path: '/openai/creds/:instance',
    readOnly: true,
    summary: 'Lista credenciais OpenAI',
    params: [instanceParam],
  },
  {
    id: 'chatbot.openai.deleteCreds',
    domain: 'chatbot',
    method: 'DELETE',
    path: '/openai/creds/:openaiCredsId/:instance',
    readOnly: false,
    summary: 'Exclui credenciais OpenAI',
    params: [
      instanceParam,
      { name: 'openaiCredsId', in: 'path', type: 'string', required: true, desc: 'ID das credenciais OpenAI' },
    ],
  },
  {
    id: 'chatbot.openai.getModels',
    domain: 'chatbot',
    method: 'GET',
    path: '/openai/getModels/:instance',
    readOnly: true,
    summary: 'Lista modelos OpenAI disponíveis',
    params: [instanceParam],
  },
  {
    id: 'chatbot.openai.create',
    domain: 'chatbot',
    method: 'POST',
    path: '/openai/create/:instance',
    readOnly: false,
    summary: 'Cria um bot OpenAI',
    params: [
      ...chatbotBaseParams,
      { name: 'credsId', in: 'body', type: 'string', required: true, desc: 'ID das credenciais OpenAI' },
      { name: 'model', in: 'body', type: 'string', required: true, desc: 'Modelo OpenAI a usar' },
      { name: 'systemMessages', in: 'body', type: 'array', required: false, desc: 'Mensagens de sistema' },
      { name: 'assistantMessages', in: 'body', type: 'array', required: false, desc: 'Mensagens do assistente' },
      { name: 'userMessages', in: 'body', type: 'array', required: false, desc: 'Mensagens do usuário' },
      { name: 'maxTokens', in: 'body', type: 'number', required: false, desc: 'Máximo de tokens por resposta' },
    ],
  },
  {
    id: 'chatbot.openai.find',
    domain: 'chatbot',
    method: 'GET',
    path: '/openai/find/:instance',
    readOnly: true,
    summary: 'Lista bots OpenAI da instância',
    params: [instanceParam],
  },
  {
    id: 'chatbot.openai.fetch',
    domain: 'chatbot',
    method: 'GET',
    path: '/openai/fetch/:openaiBotId/:instance',
    readOnly: true,
    summary: 'Obtém detalhes de um bot OpenAI',
    params: [
      instanceParam,
      { name: 'openaiBotId', in: 'path', type: 'string', required: true, desc: 'ID do bot OpenAI' },
    ],
  },
  {
    id: 'chatbot.openai.update',
    domain: 'chatbot',
    method: 'PUT',
    path: '/openai/update/:openaiBotId/:instance',
    readOnly: false,
    summary: 'Atualiza um bot OpenAI',
    params: [
      instanceParam,
      { name: 'openaiBotId', in: 'path', type: 'string', required: true, desc: 'ID do bot OpenAI' },
      { name: 'enabled', in: 'body', type: 'boolean', required: false, desc: 'Habilitar ou desabilitar' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição' },
      { name: 'credsId', in: 'body', type: 'string', required: false, desc: 'ID das credenciais' },
      { name: 'model', in: 'body', type: 'string', required: false, desc: 'Modelo a usar' },
      { name: 'systemMessages', in: 'body', type: 'array', required: false, desc: 'Mensagens de sistema' },
      { name: 'assistantMessages', in: 'body', type: 'array', required: false, desc: 'Mensagens do assistente' },
      { name: 'userMessages', in: 'body', type: 'array', required: false, desc: 'Mensagens do usuário' },
      { name: 'maxTokens', in: 'body', type: 'number', required: false, desc: 'Máximo de tokens' },
      { name: 'triggerType', in: 'body', type: 'string', required: false, desc: 'Tipo de trigger' },
      { name: 'triggerOperator', in: 'body', type: 'string', required: false, desc: 'Operador do trigger' },
      { name: 'triggerValue', in: 'body', type: 'string', required: false, desc: 'Valor do trigger' },
      { name: 'ignoreJids', in: 'body', type: 'array', required: false, desc: 'JIDs a ignorar' },
    ],
  },
  {
    id: 'chatbot.openai.delete',
    domain: 'chatbot',
    method: 'DELETE',
    path: '/openai/delete/:openaiBotId/:instance',
    readOnly: false,
    summary: 'Exclui um bot OpenAI',
    params: [
      instanceParam,
      { name: 'openaiBotId', in: 'path', type: 'string', required: true, desc: 'ID do bot OpenAI' },
    ],
  },
  {
    id: 'chatbot.openai.settings',
    domain: 'chatbot',
    method: 'POST',
    path: '/openai/settings/:instance',
    readOnly: false,
    summary: 'Define configurações globais do OpenAI',
    params: chatbotSettingsParams,
  },
  {
    id: 'chatbot.openai.fetchSettings',
    domain: 'chatbot',
    method: 'GET',
    path: '/openai/fetchSettings/:instance',
    readOnly: true,
    summary: 'Obtém configurações globais do OpenAI',
    params: [instanceParam],
  },
  {
    id: 'chatbot.openai.changeStatus',
    domain: 'chatbot',
    method: 'POST',
    path: '/openai/changeStatus/:instance',
    readOnly: false,
    summary: 'Altera status de uma sessão OpenAI',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID da conversa' },
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Novo status: opened|closed|paused' },
    ],
  },
  {
    id: 'chatbot.openai.fetchSessions',
    domain: 'chatbot',
    method: 'GET',
    path: '/openai/fetchSessions/:openaiBotId/:instance',
    readOnly: true,
    summary: 'Lista sessões ativas do OpenAI',
    params: [
      instanceParam,
      { name: 'openaiBotId', in: 'path', type: 'string', required: true, desc: 'ID do bot OpenAI' },
    ],
  },
  {
    id: 'chatbot.openai.ignoreJid',
    domain: 'chatbot',
    method: 'POST',
    path: '/openai/ignoreJid/:instance',
    readOnly: false,
    summary: 'Adiciona ou remove JID da lista de ignorados do OpenAI',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID a ignorar/remover' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove' },
    ],
  },

  // ── CHATBOT — DIFY ────────────────────────────────────────────────────────
  {
    id: 'chatbot.dify.create',
    domain: 'chatbot',
    method: 'POST',
    path: '/dify/create/:instance',
    readOnly: false,
    summary: 'Cria um bot Dify',
    params: [
      ...chatbotBaseParams,
      { name: 'botType', in: 'body', type: 'string', required: true, desc: 'Tipo do bot: chatBot|agent|chatflow|workflow' },
      { name: 'apiUrl', in: 'body', type: 'string', required: true, desc: 'URL da API Dify' },
      { name: 'apiKey', in: 'body', type: 'string', required: true, desc: 'API Key do Dify' },
    ],
  },
  {
    id: 'chatbot.dify.find',
    domain: 'chatbot',
    method: 'GET',
    path: '/dify/find/:instance',
    readOnly: true,
    summary: 'Lista bots Dify da instância',
    params: [instanceParam],
  },
  {
    id: 'chatbot.dify.fetch',
    domain: 'chatbot',
    method: 'GET',
    path: '/dify/fetch/:difyId/:instance',
    readOnly: true,
    summary: 'Obtém detalhes de um bot Dify',
    params: [
      instanceParam,
      { name: 'difyId', in: 'path', type: 'string', required: true, desc: 'ID do bot Dify' },
    ],
  },
  {
    id: 'chatbot.dify.update',
    domain: 'chatbot',
    method: 'PUT',
    path: '/dify/update/:difyId/:instance',
    readOnly: false,
    summary: 'Atualiza um bot Dify',
    params: [
      instanceParam,
      { name: 'difyId', in: 'path', type: 'string', required: true, desc: 'ID do bot Dify' },
      { name: 'enabled', in: 'body', type: 'boolean', required: false, desc: 'Habilitar ou desabilitar' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição' },
      { name: 'botType', in: 'body', type: 'string', required: false, desc: 'Tipo do bot' },
      { name: 'apiUrl', in: 'body', type: 'string', required: false, desc: 'URL da API' },
      { name: 'apiKey', in: 'body', type: 'string', required: false, desc: 'API Key' },
      { name: 'triggerType', in: 'body', type: 'string', required: false, desc: 'Tipo de trigger' },
      { name: 'triggerOperator', in: 'body', type: 'string', required: false, desc: 'Operador do trigger' },
      { name: 'triggerValue', in: 'body', type: 'string', required: false, desc: 'Valor do trigger' },
      { name: 'ignoreJids', in: 'body', type: 'array', required: false, desc: 'JIDs a ignorar' },
    ],
  },
  {
    id: 'chatbot.dify.delete',
    domain: 'chatbot',
    method: 'DELETE',
    path: '/dify/delete/:difyId/:instance',
    readOnly: false,
    summary: 'Exclui um bot Dify',
    params: [
      instanceParam,
      { name: 'difyId', in: 'path', type: 'string', required: true, desc: 'ID do bot Dify' },
    ],
  },
  {
    id: 'chatbot.dify.settings',
    domain: 'chatbot',
    method: 'POST',
    path: '/dify/settings/:instance',
    readOnly: false,
    summary: 'Define configurações globais do Dify',
    params: chatbotSettingsParams,
  },
  {
    id: 'chatbot.dify.fetchSettings',
    domain: 'chatbot',
    method: 'GET',
    path: '/dify/fetchSettings/:instance',
    readOnly: true,
    summary: 'Obtém configurações globais do Dify',
    params: [instanceParam],
  },
  {
    id: 'chatbot.dify.changeStatus',
    domain: 'chatbot',
    method: 'POST',
    path: '/dify/changeStatus/:instance',
    readOnly: false,
    summary: 'Altera status de uma sessão Dify',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID da conversa' },
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Novo status: opened|closed|paused' },
    ],
  },
  {
    id: 'chatbot.dify.fetchSessions',
    domain: 'chatbot',
    method: 'GET',
    path: '/dify/fetchSessions/:difyId/:instance',
    readOnly: true,
    summary: 'Lista sessões ativas do Dify',
    params: [
      instanceParam,
      { name: 'difyId', in: 'path', type: 'string', required: true, desc: 'ID do bot Dify' },
    ],
  },
  {
    id: 'chatbot.dify.ignoreJid',
    domain: 'chatbot',
    method: 'POST',
    path: '/dify/ignoreJid/:instance',
    readOnly: false,
    summary: 'Adiciona ou remove JID da lista de ignorados do Dify',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID a ignorar/remover' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove' },
    ],
  },

  // ── CHATBOT — FLOWISE ─────────────────────────────────────────────────────
  {
    id: 'chatbot.flowise.create',
    domain: 'chatbot',
    method: 'POST',
    path: '/flowise/create/:instance',
    readOnly: false,
    summary: 'Cria um bot Flowise',
    params: [
      ...chatbotBaseParams,
      { name: 'apiUrl', in: 'body', type: 'string', required: true, desc: 'URL da API Flowise' },
      { name: 'apiKey', in: 'body', type: 'string', required: false, desc: 'API Key do Flowise' },
    ],
  },
  {
    id: 'chatbot.flowise.find',
    domain: 'chatbot',
    method: 'GET',
    path: '/flowise/find/:instance',
    readOnly: true,
    summary: 'Lista bots Flowise da instância',
    params: [instanceParam],
  },
  {
    id: 'chatbot.flowise.fetch',
    domain: 'chatbot',
    method: 'GET',
    path: '/flowise/fetch/:flowiseId/:instance',
    readOnly: true,
    summary: 'Obtém detalhes de um bot Flowise',
    params: [
      instanceParam,
      { name: 'flowiseId', in: 'path', type: 'string', required: true, desc: 'ID do bot Flowise' },
    ],
  },
  {
    id: 'chatbot.flowise.update',
    domain: 'chatbot',
    method: 'PUT',
    path: '/flowise/update/:flowiseId/:instance',
    readOnly: false,
    summary: 'Atualiza um bot Flowise',
    params: [
      instanceParam,
      { name: 'flowiseId', in: 'path', type: 'string', required: true, desc: 'ID do bot Flowise' },
      { name: 'enabled', in: 'body', type: 'boolean', required: false, desc: 'Habilitar ou desabilitar' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição' },
      { name: 'apiUrl', in: 'body', type: 'string', required: false, desc: 'URL da API' },
      { name: 'apiKey', in: 'body', type: 'string', required: false, desc: 'API Key' },
      { name: 'triggerType', in: 'body', type: 'string', required: false, desc: 'Tipo de trigger' },
      { name: 'triggerOperator', in: 'body', type: 'string', required: false, desc: 'Operador do trigger' },
      { name: 'triggerValue', in: 'body', type: 'string', required: false, desc: 'Valor do trigger' },
      { name: 'ignoreJids', in: 'body', type: 'array', required: false, desc: 'JIDs a ignorar' },
    ],
  },
  {
    id: 'chatbot.flowise.delete',
    domain: 'chatbot',
    method: 'DELETE',
    path: '/flowise/delete/:flowiseId/:instance',
    readOnly: false,
    summary: 'Exclui um bot Flowise',
    params: [
      instanceParam,
      { name: 'flowiseId', in: 'path', type: 'string', required: true, desc: 'ID do bot Flowise' },
    ],
  },
  {
    id: 'chatbot.flowise.settings',
    domain: 'chatbot',
    method: 'POST',
    path: '/flowise/settings/:instance',
    readOnly: false,
    summary: 'Define configurações globais do Flowise',
    params: chatbotSettingsParams,
  },
  {
    id: 'chatbot.flowise.fetchSettings',
    domain: 'chatbot',
    method: 'GET',
    path: '/flowise/fetchSettings/:instance',
    readOnly: true,
    summary: 'Obtém configurações globais do Flowise',
    params: [instanceParam],
  },
  {
    id: 'chatbot.flowise.changeStatus',
    domain: 'chatbot',
    method: 'POST',
    path: '/flowise/changeStatus/:instance',
    readOnly: false,
    summary: 'Altera status de uma sessão Flowise',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID da conversa' },
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Novo status: opened|closed|paused' },
    ],
  },
  {
    id: 'chatbot.flowise.fetchSessions',
    domain: 'chatbot',
    method: 'GET',
    path: '/flowise/fetchSessions/:flowiseId/:instance',
    readOnly: true,
    summary: 'Lista sessões ativas do Flowise',
    params: [
      instanceParam,
      { name: 'flowiseId', in: 'path', type: 'string', required: true, desc: 'ID do bot Flowise' },
    ],
  },
  {
    id: 'chatbot.flowise.ignoreJid',
    domain: 'chatbot',
    method: 'POST',
    path: '/flowise/ignoreJid/:instance',
    readOnly: false,
    summary: 'Adiciona ou remove JID da lista de ignorados do Flowise',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID a ignorar/remover' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove' },
    ],
  },

  // ── CHATBOT — N8N ─────────────────────────────────────────────────────────
  {
    id: 'chatbot.n8n.create',
    domain: 'chatbot',
    method: 'POST',
    path: '/n8n/create/:instance',
    readOnly: false,
    summary: 'Cria um bot N8N',
    params: [
      ...chatbotBaseParams,
      { name: 'apiUrl', in: 'body', type: 'string', required: true, desc: 'URL da API N8N' },
      { name: 'apiKey', in: 'body', type: 'string', required: true, desc: 'API Key do N8N' },
    ],
  },
  {
    id: 'chatbot.n8n.find',
    domain: 'chatbot',
    method: 'GET',
    path: '/n8n/find/:instance',
    readOnly: true,
    summary: 'Lista bots N8N da instância',
    params: [instanceParam],
  },
  {
    id: 'chatbot.n8n.fetch',
    domain: 'chatbot',
    method: 'GET',
    path: '/n8n/fetch/:n8nId/:instance',
    readOnly: true,
    summary: 'Obtém detalhes de um bot N8N',
    params: [
      instanceParam,
      { name: 'n8nId', in: 'path', type: 'string', required: true, desc: 'ID do bot N8N' },
    ],
  },
  {
    id: 'chatbot.n8n.update',
    domain: 'chatbot',
    method: 'PUT',
    path: '/n8n/update/:n8nId/:instance',
    readOnly: false,
    summary: 'Atualiza um bot N8N',
    params: [
      instanceParam,
      { name: 'n8nId', in: 'path', type: 'string', required: true, desc: 'ID do bot N8N' },
      { name: 'enabled', in: 'body', type: 'boolean', required: false, desc: 'Habilitar ou desabilitar' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição' },
      { name: 'apiUrl', in: 'body', type: 'string', required: false, desc: 'URL da API' },
      { name: 'apiKey', in: 'body', type: 'string', required: false, desc: 'API Key' },
      { name: 'triggerType', in: 'body', type: 'string', required: false, desc: 'Tipo de trigger' },
      { name: 'triggerOperator', in: 'body', type: 'string', required: false, desc: 'Operador do trigger' },
      { name: 'triggerValue', in: 'body', type: 'string', required: false, desc: 'Valor do trigger' },
      { name: 'ignoreJids', in: 'body', type: 'array', required: false, desc: 'JIDs a ignorar' },
    ],
  },
  {
    id: 'chatbot.n8n.delete',
    domain: 'chatbot',
    method: 'DELETE',
    path: '/n8n/delete/:n8nId/:instance',
    readOnly: false,
    summary: 'Exclui um bot N8N',
    params: [
      instanceParam,
      { name: 'n8nId', in: 'path', type: 'string', required: true, desc: 'ID do bot N8N' },
    ],
  },
  {
    id: 'chatbot.n8n.settings',
    domain: 'chatbot',
    method: 'POST',
    path: '/n8n/settings/:instance',
    readOnly: false,
    summary: 'Define configurações globais do N8N',
    params: chatbotSettingsParams,
  },
  {
    id: 'chatbot.n8n.fetchSettings',
    domain: 'chatbot',
    method: 'GET',
    path: '/n8n/fetchSettings/:instance',
    readOnly: true,
    summary: 'Obtém configurações globais do N8N',
    params: [instanceParam],
  },
  {
    id: 'chatbot.n8n.changeStatus',
    domain: 'chatbot',
    method: 'POST',
    path: '/n8n/changeStatus/:instance',
    readOnly: false,
    summary: 'Altera status de uma sessão N8N',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID da conversa' },
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Novo status: opened|closed|paused' },
    ],
  },
  {
    id: 'chatbot.n8n.fetchSessions',
    domain: 'chatbot',
    method: 'GET',
    path: '/n8n/fetchSessions/:n8nId/:instance',
    readOnly: true,
    summary: 'Lista sessões ativas do N8N',
    params: [
      instanceParam,
      { name: 'n8nId', in: 'path', type: 'string', required: true, desc: 'ID do bot N8N' },
    ],
  },
  {
    id: 'chatbot.n8n.ignoreJid',
    domain: 'chatbot',
    method: 'POST',
    path: '/n8n/ignoreJid/:instance',
    readOnly: false,
    summary: 'Adiciona ou remove JID da lista de ignorados do N8N',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID a ignorar/remover' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove' },
    ],
  },

  // ── CHATBOT — EVOAI ───────────────────────────────────────────────────────
  {
    id: 'chatbot.evoai.create',
    domain: 'chatbot',
    method: 'POST',
    path: '/evoai/create/:instance',
    readOnly: false,
    summary: 'Cria um bot EvoAI',
    params: [
      ...chatbotBaseParams,
      { name: 'agentUrl', in: 'body', type: 'string', required: true, desc: 'URL do agente EvoAI' },
      { name: 'apiKey', in: 'body', type: 'string', required: true, desc: 'API Key do EvoAI' },
    ],
  },
  {
    id: 'chatbot.evoai.find',
    domain: 'chatbot',
    method: 'GET',
    path: '/evoai/find/:instance',
    readOnly: true,
    summary: 'Lista bots EvoAI da instância',
    params: [instanceParam],
  },
  {
    id: 'chatbot.evoai.fetch',
    domain: 'chatbot',
    method: 'GET',
    path: '/evoai/fetch/:evoaiId/:instance',
    readOnly: true,
    summary: 'Obtém detalhes de um bot EvoAI',
    params: [
      instanceParam,
      { name: 'evoaiId', in: 'path', type: 'string', required: true, desc: 'ID do bot EvoAI' },
    ],
  },
  {
    id: 'chatbot.evoai.update',
    domain: 'chatbot',
    method: 'PUT',
    path: '/evoai/update/:evoaiId/:instance',
    readOnly: false,
    summary: 'Atualiza um bot EvoAI',
    params: [
      instanceParam,
      { name: 'evoaiId', in: 'path', type: 'string', required: true, desc: 'ID do bot EvoAI' },
      { name: 'enabled', in: 'body', type: 'boolean', required: false, desc: 'Habilitar ou desabilitar' },
      { name: 'description', in: 'body', type: 'string', required: false, desc: 'Descrição' },
      { name: 'agentUrl', in: 'body', type: 'string', required: false, desc: 'URL do agente' },
      { name: 'apiKey', in: 'body', type: 'string', required: false, desc: 'API Key' },
      { name: 'triggerType', in: 'body', type: 'string', required: false, desc: 'Tipo de trigger' },
      { name: 'triggerOperator', in: 'body', type: 'string', required: false, desc: 'Operador do trigger' },
      { name: 'triggerValue', in: 'body', type: 'string', required: false, desc: 'Valor do trigger' },
      { name: 'ignoreJids', in: 'body', type: 'array', required: false, desc: 'JIDs a ignorar' },
    ],
  },
  {
    id: 'chatbot.evoai.delete',
    domain: 'chatbot',
    method: 'DELETE',
    path: '/evoai/delete/:evoaiId/:instance',
    readOnly: false,
    summary: 'Exclui um bot EvoAI',
    params: [
      instanceParam,
      { name: 'evoaiId', in: 'path', type: 'string', required: true, desc: 'ID do bot EvoAI' },
    ],
  },
  {
    id: 'chatbot.evoai.settings',
    domain: 'chatbot',
    method: 'POST',
    path: '/evoai/settings/:instance',
    readOnly: false,
    summary: 'Define configurações globais do EvoAI',
    params: chatbotSettingsParams,
  },
  {
    id: 'chatbot.evoai.fetchSettings',
    domain: 'chatbot',
    method: 'GET',
    path: '/evoai/fetchSettings/:instance',
    readOnly: true,
    summary: 'Obtém configurações globais do EvoAI',
    params: [instanceParam],
  },
  {
    id: 'chatbot.evoai.changeStatus',
    domain: 'chatbot',
    method: 'POST',
    path: '/evoai/changeStatus/:instance',
    readOnly: false,
    summary: 'Altera status de uma sessão EvoAI',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID da conversa' },
      { name: 'status', in: 'body', type: 'string', required: true, desc: 'Novo status: opened|closed|paused' },
    ],
  },
  {
    id: 'chatbot.evoai.fetchSessions',
    domain: 'chatbot',
    method: 'GET',
    path: '/evoai/fetchSessions/:evoaiId/:instance',
    readOnly: true,
    summary: 'Lista sessões ativas do EvoAI',
    params: [
      instanceParam,
      { name: 'evoaiId', in: 'path', type: 'string', required: true, desc: 'ID do bot EvoAI' },
    ],
  },
  {
    id: 'chatbot.evoai.ignoreJid',
    domain: 'chatbot',
    method: 'POST',
    path: '/evoai/ignoreJid/:instance',
    readOnly: false,
    summary: 'Adiciona ou remove JID da lista de ignorados do EvoAI',
    params: [
      instanceParam,
      { name: 'remoteJid', in: 'body', type: 'string', required: true, desc: 'JID a ignorar/remover' },
      { name: 'action', in: 'body', type: 'string', required: true, desc: 'Ação: add|remove' },
    ],
  },
];
